UserDao 예외상황에 대한 처리

DB커넥션이라는 제한적인 리소스를 공유해 사용하는 서버에서 동작하는 JDBC코드가 반드시 지켜야 할 원칙 = 예외처리

정상적인 JDBC 코드의 흐름을 따르지 않고 중간에 어떤 이유로든 예외가 발생했을 경우에도 사용한 리소스를 **반드시 반환** 하도록 만들어야 하기 때문이다.

```Java
public void deleteAll() throws SQLException {
    Connection c = dataSource.getConnection();

    // 이 부분에서 예외 발생하면 바로 메서드 실행이 종료됨.
    PreparedStatement ps = c.prepareStatement("delete from users");
    ps.executeUpdate();
    // Connection과 PreparedStatement라는 두 개의 공유 리소스를 제대로 반환하지 못함.

    ps.close(); // close는 리소스를 반환한다는 의미로 이해하자.
    c.close();
}
```

일반적으로 서버에서는 제한된 개수의 DB커넥션을 만들어서 재사용 가능한 풀로 관리한다.
DB풀은 getConnection()으로 가져간 커넥션을 명시적으로 close()해서 돌려줘야지만 다시 풀에 넣었다가 다음 커넥션 요청이 있을 때 재사용할 수 있다.
그런데 이런 식으로 오류가 날 때마다 미처 반환되지 못한 Connection이 계속 쌓이면
어느 순간에 커넥션 풀에 여유가 없어지고 리소스가 모자란다는 심각한 오류를 내며 서버가 중단될 수 있다. 따라서 위 코드는 장시간 운영되는 다중 사용자를 위한 서버에 적용하기에는 위험하다.

pool 방식
미리 정해진 pool 안에 제한된 수의 리소스(Connection, Statement)를 만들어두고 필요할 때 이를 할당하고, 반환하면 다시 풀에 넣는 방식으로 운영된다.

=> 요청이 매우 많은 서버환경에서는 매번 새로운 리소스를 생성하는 대신 풀에 미리 만들어둔 리소스를 돌려가며 사용하는 편이 훨씬 유리하다. 대신, 사용한 리소스는 빠르게 반환해야 한다. 그렇지 않으면 풀에 있는 리소스가 고갈되고 결국 문제 발생한다. 여기서 리소스를 풀로 다시 돌려주는 역할은 close() 메서드가 한다.

그래서 JDBC 코드에서는 어떠한 상황에서도 가져온 리소스를 반환하도록
try/catch/finally 구문 사용을 권장하고 있다.

try블록 예외가 발생할 가능성이 있는 코드를 묶어줌.
catch블록 예외가 발생했을 때 부가적인 작업을 하기 위함.
finally try블록에서 예외가 발생했을 때나 안 했을 때나 모두 실행됨.

```java
public void deleteAll() throws SQLException {
    Connection c = null;
    PreparedStatement ps = null;

    // 1.
    // try 블록안에서도 특히 어느 시점에 예외가 발생하느냐에 따라서
    // 어느 것(공유하고 있는 리소스들)의 close()메서드를 호출해야할지가 달라짐.
    try {
        c = dataSource.getConnection(); // <case 1>
        ps = c.prepareStatement("delete from users"); // <case 2>
        ps.executeUpdate();
    } catch (SQLException e) {
        throw e;
    } finally {
        // null 체크를 해서 리소스를 가져온 경우에만 반환하도록 한다.
        // 그렇지 않으면 NullPointerException 발생함.
        if( ps != null ){
            try{
                ps.close();
            } catch (SQPException e){ // close() 메서드도 SQLException이 발생할 수 있는 메서드다!
                  // 하지만 close가 실패했을 때는 특별히 해줄 조치는 없어서 비어있다.
                  // 그렇다고 try/catch블록 없애면 안됨. 여기서 예외발생하면 다음에 반환할 connection을 반환할 수 없음.
            }
        }

        if( c != null ){
              try{
                  c.close();
              } catch (SQLException e){
                  // catch 블록은 보통 예외가 발생한 경우에 로그를 남기는 등 부가작업에 쓰인다.
              }
        }
    }
}
```

### JDBC 조회 기능의 예외처리
ResultSet이 추가되므로 코드가 좀 더 복잡해진다.
